[[headers]]
  for = "/*"
[headers.values]
Strict-Transport-Security: "max-age=31536000; includeSubDomains"
X-Content-Type-Options: "nosniff"
X-Frame-Options: "SAMEORIGIN"
X-XSS-Protection: "1; mode=block"
Strict-Transport-Security: "max-age=31536000; includeSubdomains"
Referrer-Policy: "strict-origin-when-cross-origin"
